"""Tests for glass-box logging: correlation id, structured envelope, and safety.

Since MCP in-protocol logging was deprecated (SEP-2577), the server narrates each
tool invocation on the **stderr-native structured stream** only. These tests
exercise ``_runtime.run_tool`` and its helpers directly, asserting on the captured
structured events (``tool.received`` / ``tool.result`` / ``tool.error``) and the
correlation ``request_id`` bound via contextvars — and prove no client-facing
protocol log messages are emitted. They also cover which failures reach the WxCC
API and which are rejected before it.
"""

from __future__ import annotations

import httpx
import pytest
import structlog
from structlog.testing import capture_logs

from wxcc_mcp import _runtime
from wxcc_mcp.api.client import WxccApiClient
from wxcc_mcp.errors import AuthError, InsufficientPermissionsError, NotFoundError
from wxcc_mcp.models.schemas import CreateEntryInput, ListAddressBooksInput
from wxcc_mcp.tools import address_books, entries

from .conftest import make_handler

ORG = "org1"
SID = "s1"


class FakeCtx:
    """A stand-in MCP context that records any client-facing log calls.

    The server no longer emits in-protocol logs, so in these tests ``logs`` is
    expected to stay empty — it exists purely to prove that no
    ``notifications/message`` traffic is generated by a tool run.
    """

    def __init__(self) -> None:
        self.logs: list[tuple[str, str]] = []

    async def debug(self, message: str) -> None:
        self.logs.append(("debug", message))

    async def info(self, message: str) -> None:
        self.logs.append(("info", message))

    async def warning(self, message: str) -> None:
        self.logs.append(("warning", message))

    async def error(self, message: str) -> None:
        self.logs.append(("error", message))


class _Result:
    """Minimal stand-in for a pydantic output object."""

    def __init__(self, payload: dict) -> None:
        self._payload = payload

    def model_dump(self, mode: str = "json") -> dict:
        return self._payload


def _event(logs: list[dict], name: str) -> dict:
    """Return the first captured structlog event with ``event == name``."""
    for entry in logs:
        if entry.get("event") == name:
            return entry
    raise AssertionError(f"no {name!r} event in {[e.get('event') for e in logs]!r}")


# --- helpers ---------------------------------------------------------------


def test_new_request_id_is_short_hex_and_unique() -> None:
    ids = {_runtime._new_request_id() for _ in range(50)}
    assert len(ids) == 50  # unique at lab scale
    for rid in ids:
        assert len(rid) == 6
        int(rid, 16)  # valid hex


def test_result_summary_variants() -> None:
    assert "item(s)" in _runtime._result_summary({"total_returned": 5})
    assert "dry-run" in _runtime._result_summary({"dry_run": True})
    assert "committed" in _runtime._result_summary({"committed": True, "resource_id": "x"})
    assert "create" in _runtime._result_summary({"to_create": 1, "to_update": 0, "to_delete": 0})
    assert _runtime._result_summary({"error": "boom"}) == "boom"


# --- structured envelope + correlation -------------------------------------


async def test_run_tool_success_emits_correlated_structured_events() -> None:
    observed: dict = {}

    async def factory() -> _Result:
        observed.update(structlog.contextvars.get_contextvars())
        return _Result({"total_returned": 3})

    with capture_logs() as logs:
        out = await _runtime.run_tool(factory, None, tool_name="list_x", intent="listing things")

    assert out == {"total_returned": 3}

    received = _event(logs, "tool.received")
    result = _event(logs, "tool.result")
    assert received["tool"] == "list_x"
    assert received["intent"] == "listing things"
    assert "item(s)" in result["summary"]
    assert "elapsed_ms" in result

    # A correlation id was bound for downstream server-side records to inherit.
    assert observed["tool"] == "list_x"
    assert len(observed["request_id"]) == 6
    int(observed["request_id"], 16)  # valid hex


async def test_run_tool_translates_wxcc_error_to_structured_error() -> None:
    async def factory() -> _Result:
        raise NotFoundError("missing")

    with capture_logs() as logs:
        out = await _runtime.run_tool(factory, None, tool_name="get_x", intent="x")

    assert "error" in out and "Not found" in out["error"]
    error = _event(logs, "tool.error")
    assert "Not found" in error["error"]
    assert error["tool"] == "get_x"


async def test_run_tool_surfaces_validation_error() -> None:
    async def factory() -> _Result:
        raise ValueError("Phone number '05' is not valid E.164 (e.g. +14155551234).")

    with capture_logs() as logs:
        out = await _runtime.run_tool(factory, None, tool_name="create_entry", intent="x")

    assert out["error"].startswith("Phone number")
    error = _event(logs, "tool.error")
    assert error["error"].startswith("Phone number")


async def test_ids_differ_across_invocations_and_do_not_leak() -> None:
    seen: list[str] = []

    async def factory() -> _Result:
        seen.append(structlog.contextvars.get_contextvars().get("request_id"))
        return _Result({})

    await _runtime.run_tool(factory, None, tool_name="t")
    await _runtime.run_tool(factory, None, tool_name="t")

    assert seen[0] != seen[1]
    # Context is torn down after each invocation — no id leaks to the next.
    assert "request_id" not in structlog.contextvars.get_contextvars()


async def test_run_tool_emits_no_client_protocol_logs() -> None:
    """The deprecated in-protocol logging path must never be exercised."""

    async def ok() -> _Result:
        return _Result({"committed": True})

    async def boom() -> _Result:
        raise NotFoundError("missing")

    ctx = FakeCtx()
    assert await _runtime.run_tool(ok, ctx, tool_name="t", intent="i") == {"committed": True}
    assert "error" in await _runtime.run_tool(boom, ctx, tool_name="t", intent="i")

    # No ctx.info/warning/error was called → no notifications/message traffic.
    assert ctx.logs == []


async def test_run_tool_runs_without_a_context() -> None:
    async def factory() -> _Result:
        return _Result({"committed": True})

    assert await _runtime.run_tool(factory, None, tool_name="t") == {"committed": True}


async def test_no_secret_leaks_into_structured_logs() -> None:
    async def factory() -> _Result:
        return _Result({"committed": True, "resource_id": "ab-new"})

    with capture_logs() as logs:
        await _runtime.run_tool(
            factory, None, tool_name="create_address_book", intent="create book (commit=True)"
        )

    blob = " ".join(str(v) for entry in logs for v in entry.values()).lower()
    for needle in ("bearer", "access_token", "refresh_token", "authorization", "secret"):
        assert needle not in blob


# --- which failures reach the API (the troubleshooting contrast) -----------


async def test_e164_validation_makes_no_api_call(client) -> None:
    with capture_logs() as logs:
        with pytest.raises(ValueError):
            await entries.run_create(
                client,
                SID,
                CreateEntryInput(
                    org_id=ORG, address_book_id="ab1", name="Bad", number="05", confirm=True
                ),
            )
    assert "wxcc_api_call" not in [entry.get("event") for entry in logs]


async def test_missing_token_makes_no_api_call() -> None:
    class FailingBroker:
        async def get_valid_token(self, session_id: str) -> str:
            raise AuthError("Not authorized: complete the Webex OAuth sign-in.")

    http = httpx.AsyncClient(transport=httpx.MockTransport(make_handler()))
    client = WxccApiClient(FailingBroker(), http_client=http)  # type: ignore[arg-type]
    try:
        with capture_logs() as logs:
            with pytest.raises(AuthError):
                await address_books.run_list(client, SID, ListAddressBooksInput(org_id=ORG))
        assert "wxcc_api_call" not in [entry.get("event") for entry in logs]
    finally:
        await client.aclose()


async def test_permission_denied_does_make_an_api_call(client_factory) -> None:
    client = client_factory(errors={"address_book": 403})
    with capture_logs() as logs:
        with pytest.raises(InsufficientPermissionsError):
            await address_books.run_list(client, SID, ListAddressBooksInput(org_id=ORG))
    assert "wxcc_api_call" in [entry.get("event") for entry in logs]
